service: email-api

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1
  environment:
  SOURCE_EMAIL: "harshit@example.com"
  AWS_REGION: "ap-south-1"


functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send-email
          method: post
          cors: true

plugins:
  - serverless-offline

